### ISSUE TITLE
git-fetch cause "429 Too Many Requests"

### ISSUE THREAD

**Issue by ybiquitous** [sider/runners#1233]
The following error sometimes occurs:

> git-fetch failed: fatal: unable to access 'https://[FILTERED]@github.com/org/repo/': The requested URL returned error: 429 

The code location:

https://github.com/sider/runners/blob/224ad45bfe07974ee85037c272413fd088306052/lib/runners/workspace/git.rb#L33

**Comment by ybiquitous** [comment]
If the error is raised due to a rate limit over, we may need to return a new error.
The Runners caller can retry the execution of Runners when it receives the new error.

**Comment by yykamei** [comment]
* eightcard: There are [17](https://app.bugsnag.com/sleeek-corporation/runners/errors/5ec4f901d42bbb001725abad?filters[event.since][0][type]=eq&filters[event.since][0][value]=30d&filters[error.status][0][type]=eq&filters[error.status][0][value]=open&filters[search][0][type]=eq&filters[search][0][value]=429%20&filters[search][1][type]=eq&filters[search][1][value]=eightcard) errors within 2 weeks
* crowdworksjp: There [21](https://app.bugsnag.com/sleeek-corporation/runners/errors/5ec4f901d42bbb001725abad?filters[event.since][0][type]=eq&filters[event.since][0][value]=30d&filters[error.status][0][type]=eq&filters[error.status][0][value]=open&filters[search][0][type]=eq&filters[search][0][value]=429&filters[search][1][type]=eq&filters[search][1][value]=crowdworksjp) errors within 2 weeks
* padlet: There [40](https://app.bugsnag.com/sleeek-corporation/runners/errors/5ec4f901d42bbb001725abad?filters[event.since][0][type]=eq&filters[event.since][0][value]=30d&filters[error.status][0][type]=eq&filters[error.status][0][value]=open&filters[search][0][type]=eq&filters[search][0][value]=429&filters[search][1][type]=eq&filters[search][1][value]=mozart) errors within 2 weeks

The correlation between the number of repositories and the error rate does not look sufficient to explain the error :thinking:

**Comment by ybiquitous** [comment]
@yykamei How about increasing retry count and interval?

**Comment by yykamei** [comment]
Yes, the only thing we can is just retrying for now. I will implement it.

**Comment by ybiquitous** [comment]
@yykamei Can we close this issue?

**Comment by yykamei** [comment]
Yes, I closed.
