### ISSUE TITLE
Support Git URL that includes more than 2 nested paths like https://example.com/foo/bar/project

### ISSUE THREAD

**Issue by yykamei** [sider/runners#1403]
Runners assume the Git remote URL has one parent path and its child path, such as `https://example.com/foo/project`. We call `foo` as an `owner` and `project` as a `repo`, and they are used to construct a Git remote URL here.

https://github.com/sider/runners/blob/50ebb5be65433470547126ec0acb022a838b807d/lib/runners/workspace/git.rb#L64

However, I want Runners to handle a remote URL with more than two nested paths like `https://example.com/foo/bar/project`. To support such URLs, I want to make Runners handle `git_http_url` as a complete Git remote URL and remove `owner` and `repo` from `Options::GitSource`.

What do you think?

**Comment by ybiquitous** [comment]
I agree. I think `owner` and `repo` are needless, and we need just `git_http_url` and `git_http_userinfo`.

Furthermore, the name `git_http_url` seems a bit confusing to me because `file://...` is acceptable in the smoke test.

https://github.com/sider/runners/blob/50ebb5be65433470547126ec0acb022a838b807d/lib/runners/workspace/git.rb#L60

So, I suggest:

- Remove `owner` and `repo`
- Rename `git_http_url` to `git_url`
- Rename `git_http_userinfo` to `git_url_userinfo`

**Comment by yykamei** [comment]
Thank you for your feedback.

> So, I suggest:
> 
> * Remove `owner` and `repo`
> * Rename `git_http_url` to `git_url`
> * Rename `git_http_userinfo` to `git_url_userinfo`

It makes sense.
