### ISSUE TITLE
[Metrics File Info] Invoking git-log(1) for each file takes long time

### ISSUE THREAD

**Issue by yykamei** [sider/runners#2028]
Some repositories have too many files, and it could be time-consuming to invoke git-log(1) for each file here.

https://github.com/sider/runners/blob/337f67cab276e6e2b584504ccc920496aaadc3f4/lib/runners/processor/metrics_fileinfo.rb#L80-L83

I came up with an idea to make this feature possibly faster. The algorithm follows these steps:

1. Prepare a `Hash` to store Git metadata for each file
    - At this point, the `Hash` contains all file paths with `nil` value respectively
2. Run `git log --reverse --name-status --format=format:%aI`
3. Iterate the output of the previous command commit by commit and update the prepared `Hash`
    - e.g., `{ "app/models/user.rb" => timestamp }` will be updated with a new timestamp
    - File names appearing in the output may contain **renamed** or **deleted** files. Check a file name is in the `Hash` to avoid including nonexistent files
4. After this processing, we could get a `Hash` data storing Git metadata for each path

What do you think?

**Comment by gnakagaw** [comment]
> Some repositories have too many files, and it could be time-consuming to invoke git-log(1) for each file here.

It seems that the cause is not `git` process creation itself but processing time for each `git log` operation. Anyway, we have to change the algorithm to get last commit date.

Here is a simple benchmark result to measure `git log` execution time. The target is [DefinitelyTyped/DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped ) repository: a super large repository. I executed a command as below.
```find . -not -type d -not -path './.git/*'  -exec bash -c "echo -n "{}," && /usr/bin/time -f \"%e\" git log -1 {} > /dev/null" > ~/time.csv 2>&1 \;```

You can see that the analysis time is various. (e.g. 39.2 seconds, 0.06 seconds, etc..). Thus, the issue is not depend on number of files. I guess that it depends on number of commits. (The target repo has 73928 commit...).  `git log -1` operation execute full commit tree scan for each file. This operations seems to make large overhead if the tree is large. 

| Target Filename                                          | Execution time (seconds) |
|----------------------------------------------------------|--------------------------|
| ./types/wicg-mediasession/tslint.json                    | 39.2                     |
| ./types/playerframework/playerframework-tests.ts         | 35.47                    |
| ./types/uuid-1345/uuid-1345-tests.ts                     | 35.36                    |
| ./types/uuid-1345/index.d.ts                             | 35.3                     |
| (skipped)                                                | …                        |
| ./types/react-native-autocomplete-input/v3/tsconfig.json | 11.36                    |
| ./types/react-dev-utils/webpackHotDevClient.d.ts         | 11.35                    |
| ./types/vuedraggable/vuedraggable-tests.ts               | 11.35                    |
| ./types/tsc-watch/tsc-watch-tests.ts                     | 11.34                    |
| ./types/validator/lib/ltrim.d.ts                         | 11.34                    |
| ./types/react-google-places-suggest/tslint.json          | 11.33                    |
| (skipped)                                                | …                        |
| ./types/meteor-astronomy/tslint.json                     | 9.75                     |
| ./types/react-photoswipe/tsconfig.json                   | 9.74                     |
| ./types/command-line-args/index.d.ts                     | 9.73                     |
| ./types/multiplexjs/index.d.ts                           | 9.72                     |
| (skipped)                                                | …                        |
| ./types/react-select/src/builtins.d.ts                   | 0.32                     |
| ./types/react-select/src/components/Input.d.ts           | 0.32                     |
| ./types/react-select/src/components/Control.d.ts         | 0.32                     |
| ./types/react-select/src/components/index.d.ts           | 0.32                     |
| ./types/react-select/test/examples/FixedOptions.tsx      | 0.32                     |
| ./types/hapi__basic/package.json                         | 0.32                     |
| (skipped)                                                | …                        |
| ./types/pulsar-client/index.d.ts                         | 0.08                     |
| ./types/gbk.js/index.d.ts                                | 0.07                     |
| ./types/gbk.js/tsconfig.json                             | 0.07                     |
| ./types/gbk.js/tslint.json                               | 0.07                     |
| ./types/rax/index.d.ts                                   | 0.07                     |
| ./dangerfile.ts                                          | 0.06                     |
| ./types/smtp-server/index.d.ts                           | 0.06                     |
| ./types/greasemonkey/greasemonkey-tests.ts               | 0.06                     |
| (skipped)                                                | …                        |

**Comment by gnakagaw** [comment]
> I came up with an idea to make this feature possibly faster. The algorithm follows these steps:
> 
> 1. Prepare a `Hash` to store Git metadata for each file
>    
>    * At this point, the `Hash` contains all file paths with `nil` value respectively
> 2. Run `git log --reverse --name-status --format=format:%aI`
> 3. Iterate the output of the previous command commit by commit and update the prepared `Hash`
>    
>    * e.g., `{ "app/models/user.rb" => timestamp }` will be updated with a new timestamp
>    * File names appearing in the output may contain **renamed** or **deleted** files. Check a file name is in the `Hash` to avoid including nonexistent files
> 4. After this processing, we could get a `Hash` data storing Git metadata for each path

Thanks. This looks good to me. We only have to scan the commit tree once with your proposed method. I benchmarked `git log --reverse --name-status --format=format:%aI > /dev/null` It tooks only 19.610 seconds.

**Comment by gnakagaw** [comment]
NOTE: I faced warning messages when I execute `git log --reverse --name-status...` command in a large repository. We have to examine the message.
```
warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your diff.renameLimit variable to at least 1803 and retry the command.
```

**Comment by gnakagaw** [comment]
related: https://stackoverflow.com/questions/35186829/how-to-improve-git-log-performance

**Comment by gnakagaw** [comment]
I found [Git's pre-cache mechanism (commit-graph)](https://git-scm.com/docs/git-commit-graph/2.30.0). It reduce `git-log` cost dramatically. I'll try to use this.

```
analyzer_runner@24c44f860a83:/tmp/DefinitelyTyped$ time git log --oneline -1 types/wicg-mediasession/tslint.json
bbc61fbf93 Extend "dtslint/dt.json" directly instead of "../tslint.json". (#15822)

real    0m14.382s
user    0m14.241s
sys     0m0.134s
analyzer_runner@24c44f860a83:/tmp/DefinitelyTyped$ time git commit-graph write --reachable --changed-paths
Computing commit changed paths Bloom filters: 100% (74050/74050), done.

real    0m22.614s
user    0m22.480s
sys     0m0.113s
analyzer_runner@24c44f860a83:/tmp/DefinitelyTyped$ time git log --oneline -1 types/wicg-mediasession/tslint.json
bbc61fbf93 Extend "dtslint/dt.json" directly instead of "../tslint.json". (#15822)

real    0m0.108s
user    0m0.087s
sys     0m0.020s
analyzer_runner@24c44f860a83:/tmp/DefinitelyTyped$ 

```

**Comment by yykamei** [comment]
Thank you. I agree to use git-commit-graph(1). It would be better to use caching as we don't have to change code much.
