### ISSUE TITLE
[Rails Best Practices] Drop support - deadline2021-09-30

### ISSUE THREAD

**Issue by ybiquitous** [sider/runners#2320]
Rails Best Practices seems inactive for a long time. See below:
https://github.com/flyerhzm/rails_best_practices/pulse/monthly

Should we drop the support of the tool? We have alternatives below:

- RuboCop Rails
- Slim-Lint
- HAML-Lint
- ERB Lint (#2033) - not supported yet

**Comment by ybiquitous** [comment]
We have decided to drop the support at the MTG today.

**Comment by ybiquitous** [comment]
### Schedule

1. Mark deprecated and show deadline
2. Drop the support

**Comment by ybiquitous** [comment]
> 1. Mark deprecated
> 2. Decide deadline

See #2357

**Comment by radomirbosak** [comment]
For reference, here are PRs for removal of different linters from the past:
* https://github.com/sider/runners/pull/2515
* https://github.com/sider/runners/pull/1164

**Comment by radomirbosak** [comment]
> > 1. Mark deprecated
> > 2. Decide deadline
> 
> See #2357

Looks like RBP decided to release a new version one day after we marked it as deprecated :sweat_smile: 
![image](https://user-images.githubusercontent.com/4988740/151724833-dc467fdc-a092-4bff-8e77-22ff0c9b5b34.png)

Some releases were made since then, but the changelog isn't overwhelming 
https://github.com/flyerhzm/rails_best_practices/blob/master/CHANGELOG.md
